Feature/setup
shyusu4/Hello-Rails-React pull request #1
Opened 2023-01-25 19:45 UTC by shyusu4

## PR Description

- Created a new Rails app called 'hello-rails-react'
- Used the command `rails new -j webpack my_new_rails_app` as described
- Created a table for storing 5 different greetings
- Created an API endpoint that selects a random greeting from the table
- Created a static view that is the root of the app
- Created the `App` component with react-router and rendered it in the static view
- Created the `Greeting` component that displays a random greeting
- Created a `store` and a `reducer` that connects to the API endpoint

2023-01-25 21:09 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Shahrizoda, 
 ### You have been doing a tremendous job so far :ok_hand:

## To Highlight 🎉
No linter errors. :heavy_check_mark:
Git flow is followed. :heavy_check_mark:
## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
**_Note: Please do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-25 21:09 UTC, SajjadAhmad14 commented on README.md
> +### Setup
Please add commands to install dependencies, and set up database here as README should have all the information for user to start with the project.

2023-01-25 21:09 UTC, SajjadAhmad14 commented on app/javascript/src/App.js
> +      <Route path="/" element={<Greeting />} />
App does not show any greeting but when I try to go to the route `api/v1/greetings` it returns a JSON which is a greeting. Kindly make sure the app shows a random greeting.
![tests](https://user-images.githubusercontent.com/35504149/214691346-1e741e73-c94e-4219-8e26-568858bd2f31.png)

2023-01-26 07:57 UTC, shyusu4 commented on app/javascript/src/App.js
> +      <Route path="/" element={<Greeting />} />
Hi @SajjadAhmad14, thank you for the review. I'm able to see the random greeting on my end, so I'm not sure what the issue is. I'll look into it. 👍

2023-01-26 08:53 UTC, t-yanick approved these changes
Hi @shyusu4 , 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: We documented procedure on how to run your app
:heavy_check_mark:  Good job uploading a screenshot of the greeting displaying at your end in the PR
:heavy_check_mark:  Descriptive PR

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-26 10:52 UTC, merged